Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "vm2-desde-terraform"
      
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vm2-creada-desde-vm1"
    vb.memory = "1024"
    vb.cpus = 1
  end
      
  config.vm.network "private_network", ip: "192.168.50.20"
  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.network "forwarded_port", guest: 22, host: 2223, id: "ssh"
      
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    echo "VM2 lista"
  SHELL
end
