version: "2"
services:
  haproxy:
    build: ./haproxy
    links:
      - web1
      - web2
      - web3
      - web4
      - web5
    ports:
      - "5080:80"

  web1:
    build: ./web
    volumes:
      - ./web/html1:/var/www/html/

  web2:
    build: ./web
    volumes:
      - ./web/html2:/var/www/html/

  web3:
    build: ./web
    volumes:
      - ./web/html3:/var/www/html/

  web4:
    build: ./web
    volumes:
      - ./web/html4:/var/www/html/

  web5:
    build: ./web
    volumes:
      - ./web/html5:/var/www/html/
