services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: myflaskapp
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  users:
    build:
      context: .
      dockerfile: microUsers/Dockerfile
    restart: always
    ports:
      - "5002:5002"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: myflaskapp
      CONSUL_HOST: consul
      SERVICE_ADDRESS: 192.168.80.3
    depends_on:
      - db
      - consul

  products:
    build:
      context: .
      dockerfile: microProducts/Dockerfile
    restart: always
    ports:
      - "5003:5003"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: myflaskapp
      CONSUL_HOST: consul
      SERVICE_ADDRESS: 192.168.80.3
    depends_on:
      - db
      - consul

  orders:
    build:
      context: .
      dockerfile: microOrders/Dockerfile
    restart: always
    ports:
      - "5004:5004"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: myflaskapp
      CONSUL_HOST: consul
      SERVICE_ADDRESS: 192.168.80.3
    depends_on:
      - db
      - consul

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - users
      - products

  consul:
    image: hashicorp/consul:1.15
    restart: always
    ports:
      - "8500:8500"
    volumes:
      - consul_data:/consul/data
    command: ["consul", "agent", "-server", "-bootstrap-expect=1", "-ui", "-bind=0.0.0.0", "-client=0.0.0.0", "-data-dir=/consul/data"]

volumes:
  db_data:
  consul_data:
