version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5001:5001"
    # El frontend sirve HTML/JS; los JS llaman a 192.168.50.4:5002/5003 como en tu código

  microusers:
    build: ./microUsers
    container_name: microusers
    ports:
      - "5002:5002"
    # Corre su propio MariaDB interno accesible como localhost para la app (sin cambios de código)

  microproducts:
    build: ./microProducts
    container_name: microproducts
    ports:
      - "5003:5003"
    # Igual que microusers: DB local interna

