# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :servidorWeb do |servidorWeb|
    servidorWeb.vm.box = "bento/ubuntu-22.04"
    servidorWeb.vm.network :private_network, ip: "192.168.50.4"
    servidorWeb.vm.provision "file", source: "iniciar_microservicios.sh", destination: "/home/vagrant/iniciar_microservicios.sh"
    servidorWeb.vm.provision "file", source: "frontend", destination: "/home/vagrant/frontend"
    servidorWeb.vm.provision "file", source: "microUsers", destination: "/home/vagrant/microUsers"
    servidorWeb.vm.provision "file", source: "microUsers/init.sql", destination: "/home/vagrant/init_users.sql"
    servidorWeb.vm.provision "file", source: "microProducts", destination: "/home/vagrant/microProducts"
    servidorWeb.vm.provision "file", source: "microProducts/init.sql", destination: "/home/vagrant/init_products.sql"
    servidorWeb.vm.provision "file", source: "consul.json", destination: "/home/vagrant/consul.json"
    servidorWeb.vm.provision "file", source: "consul.service", destination: "/home/vagrant/consul.service"
    servidorWeb.vm.provision "shell", path: "script.sh"
    servidorWeb.vm.hostname = "servidorWeb"
  end
end
