# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

config.vm.define :servidorUbuntu do |servidorUbuntu|
    servidorUbuntu.vm.box = "bento/ubuntu-22.04"
    servidorUbuntu.vm.network :private_network, ip: "192.168.100.3"
    servidorUbuntu.vm.hostname = "servidorUbuntu"
    servidorUbuntu.vm.synced_folder "hello-node", "/home/vagrant/hello-node"
    servidorUbuntu.vm.synced_folder "service", "/home/vagrant/service"
    servidorUbuntu.vm.synced_folder "rolling-app", "/home/vagrant/rolling-app"
    servidorUbuntu.vm.provision "shell", path: "provision_docker.sh"
    servidorUbuntu.vm.provision "shell", path: "provision_k8s.sh"
    servidorUbuntu.vm.provision "shell", path: "provision_practica7.sh"
    servidorUbuntu.vm.provision "shell", path: "provision_ingress.sh"
    servidorUbuntu.vm.provider "virtualbox" do |v|
        v.cpus = 2
        v.memory = 3072
    end
  end
end
