apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:stable
        ports:
        - containerPort: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  type: LoadBalancer
  selector:
    app: home-assistant
  ports:
  - port: 8123
    targetPort: 8123
