Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "vm-control"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vm1-terraform-control"
    vb.memory = "2048"
    vb.cpus = 2
  end
  
  config.vm.network "private_network", ip: "192.168.50.10"
  config.vm.synced_folder "./terraform", "/home/vagrant/terraform", create: true
  config.vm.synced_folder "./ansible", "/home/vagrant/ansible", create: true
  
  config.vm.provision "shell", inline: <<-SHELL
    set -e
    
    apt-get update
    apt-get install -y wget unzip openssh-client ansible sshpass
    
    cd /tmp
    wget -q https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
    unzip -o terraform_1.6.0_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    sudo chmod +x /usr/local/bin/terraform
    rm terraform_1.6.0_linux_amd64.zip
    
    terraform version
    ansible --version
    
    if [ ! -f /home/vagrant/.ssh/id_rsa ]; then
      sudo -u vagrant ssh-keygen -t rsa -b 4096 -f /home/vagrant/.ssh/id_rsa -N ""
    fi
    
    sudo -u vagrant bash -c 'cat > /home/vagrant/.ssh/config << EOL
Host host-edwin
    HostName 192.168.50.1
    User edwin
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null
EOL'
    
    sudo -u vagrant chmod 600 /home/vagrant/.ssh/config
    
    echo "======================================"
    echo "VM1 configurada con Terraform y Ansible"
    echo "======================================"
  SHELL
end
